### PR TITLE
Add GLib.Error.stack property

### LINKED ISSUE #196: GLib.Error.stack missing
GJS sets a `stack` property on all its errors, see https://gitlab.gnome.org/GNOME/gjs/-/blob/master/gi/gerror.cpp#L278

However, this property doesn't seem to exist on `GLib.Error` anymore, i.e.

```typescript
if (error instanceof GLib.Error) {
    console.info(error.stack);
}
```

no longer compiles.

It _did_ compile with types generated by the 3.x versions of ts-for-gir, so this looks like a regression.

### PR DESCRIPTION
**Pull request by swsnr**
Fixes #196

### CODE REVIEW

**Comment by swsnr** [comment]
@JumpLink This is mostly an educated guess, from looking at other injection files.  Is this correct?  How do I test this locally?

**Comment by swsnr** [comment]
Okay, I managed to run `yarn build:types:packages:gtk4` and now `GLib.Error` in `@types/glib-2.0` has a `stack` field:

GLib.Error

So presumably, this works?

**Comment by swsnr** [comment]
@JumpLink Would you take a look?

**Comment by JumpLink** [comment]
@swsnr Sorry for the late response, I'm still on parental leave at the moment. Looks good for me, thanks for the contribution!

**Pull request merged**
